### PR TITLE
Fix idempotency in `to_concepticon`

### PR DESCRIPTION
**Pull request by johenglisch**
I think I found the culprit.

### CODE REVIEW

**Comment by johenglisch** [comment]
Btw, I've been wondering about this sort key function:

https://github.com/lingpy/pysem/blob/903b6f1dd65a410031f3fcc47efe425b4d3df8ce/src/pysem/glosses.py#L343-L347

It seems it compares the part of speech of a match to a variable called `g`.  But from what I can tell `g` is just a temp variable used in the for loops right above.  Is that intentional?

**Comment by LinguList** [comment]
How bad, yes!

**Comment by LinguList** [comment]
Can you provide a quick fix?

**Comment by LinguList** [comment]
Sorry, I should of course do so. 

```python
In [1]: from pysem.glosses import MAPPINGS
In [2]: MAPPINGS["de"]["arm"]
Out[2]: [['1674', 'POOR', 7, 'adjective', 1]]
```

**Comment by LinguList** [comment]
The rows, with the mappings, have the POS information in `row[3]`. So the correct order should be:

```python
                key=lambda x: (x[-1], 1 if pos == x[-2] else 0, x[-3]),
```

`pos` is the part of speech that has been passed directly or not. If it is present and matches, it should be preferred, therefore we give 1.

**Comment by johenglisch** [comment]
Okay, thanks, I implemented the fix.

>`['1674', 'POOR', 7, 'adjective', 1]`

Sry for going on another tangent but what do the elements in this list actually mean?  From context I can reconstruct:

    0: Concepticon ID
    1: Concepticon Gloss
    2: ?
    3: Part of Speech
    4: ?

(I suspect I knew the answer to this at some point and then forgot.)

**Comment by LinguList** [comment]
0: Concepticon ID
1: Concepticon Gloss
2: HOW OFTEN THIS WAS MAPPED TO THE GLOSS
3: Part of Speech
4: IF IT IS THE PRIMARY MAPPING (we use 1/0 in concepticon/mappings)

**Comment by LinguList** [comment]
The argument is: the more often you map something like "you (sg)" to Concepticon THOU, the more comfortable you are to map it another time.

**Pull request merged**
